### ISSUE TITLE
Error when using a new CRS : Problem with the synchronization with the EPSG database

### ISSUE THREAD

**Issue by mabkoz** [pyproj4/pyproj#1041] opened 2022-03-25 09:48 UTC
Hello community!

#### Problem description

I am writing a python script to convert coordinates from EPSG:4937 to EPSG:9895. I am facing an error which is that the EPSG:9895 is not a valid CRS " _Invalid projection: EPSG:9895 (Internal Proj Error: proj_create: crs not found)._ " . When I go to https://epsg.org/ , I can find the CRS in the EPSG Dataset : v10.058. Correct if I am wrong but I think that the pyproj does not take into consideration the latest version of the Dataset which is v10.058.

```python
trans_group = TransformerGroup(CRS("EPSG:4937").to_3d(),CRS("EPSG:9895").to_3d())
```

**Could you please tell me how to force pyProj to synchronize with the latest version of EPSG Dataset in order to recognize my CRS ? Thank you in advance!**

#### Expected Output

I expect the code to convert the coordinates from EPSG:4937 to EPSG:9895

```python

## compute transformation
# LUREF2020 Bursa is computing 3D information (input N,E,U / lat, long, h)
print(trans_group.transformers[0].transform(49.54779150, 6.323181283, 217.401))

```
The result is supposed to be : (68133.95971970388, 91221.13528438336, 169.58002639748156) , but I encounter the error.

#### Environment Information
- pyproj -v : 
pyproj info:
    pyproj: 3.3.0
      PROJ: 8.0.1
PROJ DATA (recommended version): None
PROJ Database: 1.0
EPSG Database: v10.018 [2021-04-02]
ESRI Database: ArcMap 10.8.1 [2020-05-24]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\pckoz\anaconda3\python.exe
   machine: Windows-10-10.0.22000-SP0

Python deps:
   certifi: 2021.10.08
       pip: 21.2.4
setuptools: 58.0.4
    Cython: 0.29.24

 - pyproj version 3.3.0
 - PROJ version 8.0.1
 - PROJ data directory : C:\Users\pckoz\anaconda3\Library\share\proj
 - Python version : 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
 - Operation System Information : Windows-10-10.0.22000-SP0

#### Installation method
Installed with conda " conda install -c conda-forge proj-data " 

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at C:\Users\pckoz\anaconda3:
#
# Name                    Version                   Build  Channel
anaconda-project          0.10.1             pyhd3eb1b0_0
proj                      8.0.1                h1cfcee9_0    conda-forge
proj-data                 1.8                  hd8ed1ab_0    conda-forge
pyproj                    3.3.0            py39ha996c60_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
conda info

     active environment : base
    active env location : C:\Users\pckoz\anaconda3
            shell level : 1
       user config file : C:\Users\pckoz\.condarc
 populated config files : C:\Users\pckoz\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\pckoz\anaconda3  (writable)
      conda av data dir : C:\Users\pckoz\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\pckoz\anaconda3\pkgs
                          C:\Users\pckoz\.conda\pkgs
                          C:\Users\pckoz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\pckoz\anaconda3\envs
                          C:\Users\pckoz\.conda\envs
                          C:\Users\pckoz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by snowman2** [comment] 2022-03-25 18:14
Duplicate of #1040

**Closed by snowman2** 2022-03-25 18:14 UTC
Labels: bug
