### ISSUE TITLE
Coordinate conversion precision

### ISSUE THREAD

**Issue by galak75** [pyproj4/pyproj#232] opened 2019-03-28 20:07 UTC
I convert coordinates from WGS84 to NAD83-MTM8, either using Fiona or using Pyproj.
In the recent Pyproj releases, I noticed some results changed (up to 1 meter difference)

Here is the code executed:
https://gist.github.com/galak75/21b11734a3b618d05645152ee0c69ff6

And here are the observed results:

>  - six : 1.12.0
>  - shapely : 1.6.4.post2
>  - setuptools : 40.8.0
>  - pyproj : 1.9.6
>  - pip : 19.0.3
>  - munch : 2.3.2
>  - fiona : 1.8.6
>  - cligj : 0.5.0
>  - click : 7.0
>  - click-plugins : 1.0.4
>  - attrs : 19.1.0
> 
>  **** WGS84 points ****
>  entrance:        POINT (-73.553785 45.508722)
>  balcony:         POINT (-73.55413799999999 45.50908)
>  council chamber: POINT (-73.55424600000001 45.508931)
> 
>  ====== Entrance ======
>  reprojection using Fiona 1.8.6 : POINT (300597.3379533469 5040979.345668847)
>  reprojection using pyproj 1.9.6 : POINT (300597.3379533479 5040979.345668846)
>  distance (in meters) : 1.3588715263093766e-09
>  ====== Balcony ======
>  reprojection using Fiona 1.8.6 : POINT (300569.7819923731 5041019.148957729)
>  reprojection using pyproj 1.9.6 : POINT (300569.781992374 5041019.148957729)
>  distance (in meters) : 9.89530235528946e-10
>  ====== Council Chamber ======
>  reprojection using Fiona 1.8.6 : POINT (300561.3319389866 5041002.596190738)
>  reprojection using pyproj 1.9.6 : POINT (300561.3319389875 5041002.596190736)
>  distance (in meters) : 2.109174492302518e-09
> 
> ------------------------------------------------------------------------------
> 
>  - six : 1.12.0
>  - shapely : 1.6.4.post2
>  - setuptools : 40.8.0
>  - pyproj : 2.0.2
>  - pip : 19.0.3
>  - munch : 2.3.2
>  - fiona : 1.8.6
>  - cligj : 0.5.0
>  - click : 7.0
>  - click-plugins : 1.0.4
>  - attrs : 19.1.0
> 
>  **** WGS84 points ****
>  entrance:        POINT (-73.553785 45.508722)
>  balcony:         POINT (-73.55413799999999 45.50908)
>  council chamber: POINT (-73.55424600000001 45.508931)
> 
>  ====== Entrance ======
>  reprojection using Fiona 1.8.6 : POINT (300597.3379533469 5040979.345668847)
>  reprojection using pyproj 2.0.2 : POINT (300597.3379533479 5040979.34566805)
>  distance (in meters) : 7.972127379920356e-07
>  ====== Balcony ======
>  reprojection using Fiona 1.8.6 : POINT (300569.7819923731 5041019.148957729)
>  reprojection using pyproj 2.0.2 : POINT (300569.781992374 5041019.148956934)
>  distance (in meters) : 7.953500942810264e-07
>  ====== Council Chamber ======
>  reprojection using Fiona 1.8.6 : POINT (300561.3319389866 5041002.596190738)
>  reprojection using pyproj 2.0.2 : POINT (300561.3319389875 5041002.59618994)
>  distance (in meters) : 7.972127379920356e-07
> 
> ------------------------------------------------------------------------------
> 
>  - six : 1.12.0
>  - shapely : 1.6.4.post2
>  - setuptools : 40.8.0
>  - pyproj : 2.1.2
>  - pip : 19.0.3
>  - munch : 2.3.2
>  - fiona : 1.8.6
>  - cligj : 0.5.0
>  - click : 7.0
>  - click-plugins : 1.0.4
>  - attrs : 19.1.0
> 
>  **** WGS84 points ****
>  entrance:        POINT (-73.553785 45.508722)
>  balcony:         POINT (-73.55413799999999 45.50908)
>  council chamber: POINT (-73.55424600000001 45.508931)
> 
>  ====== Entrance ======
>  reprojection using Fiona 1.8.6 : POINT (300597.3379533469 5040979.345668847)
>  reprojection using pyproj 2.1.2 : POINT (300597.4646693002 5040978.328049704)
>  distance (in meters) : 1.0254782559962257
>  ====== Balcony ======
>  reprojection using Fiona 1.8.6 : POINT (300569.7819923731 5041019.148957729)
>  reprojection using pyproj 2.1.2 : POINT (300569.9087144609 5041018.131332614)
>  distance (in meters) : 1.0254849399112693
>  ====== Council Chamber ======
>  reprojection using Fiona 1.8.6 : POINT (300561.3319389866 5041002.596190738)
>  reprojection using pyproj 2.1.2 : POINT (300561.4586619718 5041001.578568787)
>  distance (in meters) : 1.0254819104332038
> 

Do you have any idea why the same longitude/latitude give such different NAD83 coordinates, depending in Pyproj release number?

Thank you

**Comment by snowman2** [comment] 2019-03-28 20:59
So, the old version of `pyproj` and the current verison of Fiona export the projection to `PROJ` strings. This can cause loss of projection information, such as the datum (See #212 and https://proj4.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems).  This was fixed in the current version, so that is likely the cause. @rouault @kbevers, are you able to verify?

**Comment by micahcochran** [comment] 2019-03-29 12:11
EPSG:32188 NAD83 / MTM zone 8 uses a Transverse Mercator projection.  Older versions of PROJ used `tmerc` algorithm as default, and the algorithm has been changed to `etmerc` as default.

If you add [`+approx`](https://proj4.org/operations/projections/tmerc.html#cmdoption-arg-approx) parameter to the projection string in  PROJ versions 6.0.0 and above (pyproj 2.1.2) it will switch back to the `tmerc` algorithm.

**Comment by snowman2** [comment] 2019-03-29 12:38
I was about to call it a day with what you posted, however, I noticed that his results remained consistent in pyproj 2.0.2 which uses the same version of PROJ as 2.1.2. So, following that logic, I am not entirely convinced that is the reason.

So, I tried out the PROJ string method to check (using pyproj 2.1.3 - from github), and these are the results:
```python
>>> from pyproj import Transformer, CRS
>>> crs = CRS("epsg:4326")
>>> crs.to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
>>> crs2 = CRS("epsg:32188")
>>> crs2.to_proj4()
'+proj=tmerc +lat_0=0 +lon_0=-73.5 +k=0.9999 +x_0=304800 +y_0=0 +datum=NAD83 +units=m +no_defs +type=crs'
>>> trans = Transformer.from_proj(4326, 32188)
# note: had to swap x/y as axis ordering flipped for latlon
>>> trans.transform(45.508722, -73.553785)
(300597.3379533479, 5040979.3456680495)
>>> trans2 = Transformer.from_proj(crs.to_proj4(), crs2.to_proj4())
>>> trans2.transform(-73.553785, 45.508722)
(300597.46466930024, 5040978.3280497035)
```
Although your solution does provide the previously expected results:
```python
>>> trans3 = Transformer.from_proj("+init=epsg:4326", "+init=epsg:32188 +approx")
>>> trans3.transform(-73.553785, 45.508722)
(300597.46466930024, 5040978.328050498)
```

**Comment by snowman2** [comment] 2019-03-30 19:06
Just for fun, I tried a couple of different combinations and here are the results:
```python
>>> trans = Transformer.from_proj("epsg:4326", "+proj=tmerc +lat_0=0 +lon_0=-73.5 +k=0.9999 +x_0=304800 +y_0=0 +datum=NAD83 +units=m +no_defs +approx")
>>> trans.transform(45.508722, -73.553785)
(300597.46466930024, 5040978.328050498)
>>> trans = Transformer.from_proj("epsg:4326", "+init=epsg:32188 +approx")
>>> trans.transform(45.508722, -73.553785)
(300597.46466930024, 5040978.328050498)
>>> trans = Transformer.from_proj("epsg:4326", "+proj=tmerc +lat_0=0 +lon_0=-73.5 +k=0.9999 +x_0=304800 +y_0=0 +datum=NAD83 +units=m +no_defs")
>>> trans.transform(45.508722, -73.553785)
(300597.46466930024, 5040978.3280497035)
>>> trans = Transformer.from_proj("epsg:4326", "epsg:32188")
>>> trans.transform(45.508722, -73.553785)
(300597.3379533479, 5040979.3456680495)
```
Both the PROJ string with `+approx` and the `+init=epsg:32188 +approx` produce the exact same results.
With out `+approx` the PROJ string version output varies ever so slightly from the PROJ string without (likely the `etmerc` change). However, the one with the largest difference between the original results is the one that does not have any conversion to a PROJ string.

**Comment by snowman2** [comment] 2019-03-30 19:30
I just looked at the Fiona code, and my original assumption was incorrect. The Fiona results and the 2.1.3 (GitHub) results match. This should be resolved in the next release. I am going to close this issue now. Feel free to reopen if you find the issue persists after the next release. Thanks for the report!

**Closed by snowman2** 2019-03-30 19:30 UTC

**Comment by galak75** [comment] 2019-04-02 14:18
First of all: thank you for such a fast answer! 

I'm not sure to fully understand. Does it mean it was a bug that is already fixed (in the next release)?
I will test it as soon as 2.1.3 is available.

**Comment by snowman2** [comment] 2019-04-02 17:09
> Does it mean it was a bug that is already fixed (in the next release)?

It definitely works in the next release in the current release. You just need to modify your input from `{'init': 'epsg:32188', 'no_defs': True}` to just `epsg:32188`.

```python
>>> from pyproj import Transformer
>>> trans = Transformer.from_proj("epsg:4326", {'init': 'epsg:32188', 'no_defs': True})
>>> trans.transform(45.508722, -73.553785)
(300597.46466930024, 5040978.3280497035)
>>> trans = Transformer.from_proj("epsg:4326", "epsg:32188")
>>> trans.transform(45.508722, -73.553785)
(300597.3379533479, 5040979.3456680495)
```

The reason being that the first version is loosing projection information in the conversion to a PROJ string.

**Comment by galak75** [comment] 2019-04-02 17:26
@snowman2 : Thank you again for being so responsive! it's really appreciated!

**Comment by snowman2** [comment] 2019-04-02 17:45
Not a problem! Side note: be careful with the updated version as the x/y input is swapped to lat/lon instead of the original lon/lat version. See: https://proj4.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent
