### ISSUE TITLE
SHA256 mismatch on 'no_kv_README.txt' with 'pyproj sync --all'

### ISSUE THREAD

**Issue by gwerbin** [pyproj4/pyproj#1125] opened 2022-08-26 15:41 UTC
#### Code sample

```sh
.venv/bin/pyproj sync --verbose --all
```

```
Downloading: https://cdn.proj.org/no_kv_README.txt
Traceback (most recent call last):
  File "/Users/gwerbin/Tive/software/data-science-apis/.venv/bin/pyproj", line 8, in <module>
    sys.exit(main())
  File "/Users/gwerbin/Tive/software/data-science-apis/.venv/lib/python3.10/site-packages/pyproj/__main__.py", line 201, in main
    _parse_sync_command(args)
  File "/Users/gwerbin/Tive/software/data-science-apis/.venv/lib/python3.10/site-packages/pyproj/__main__.py", line 186, in _parse_sync_command
    _download_resource_file(
  File "/Users/gwerbin/Tive/software/data-science-apis/.venv/lib/python3.10/site-packages/pyproj/sync.py", line 181, in _download_resource_file
    raise RuntimeError(f"SHA256 mismatch: {short_name}")
RuntimeError: SHA256 mismatch: no_kv_README.txt% 
```

#### Problem description

I wanted to download the files!

#### Expected Output

No error

#### Environment Information

Output from `.venv/bin/pyproj -v`:

```text
pyproj info:
    pyproj: 3.3.1
      PROJ: 8.2.0
  data dir: /Users/gwerbin/Projects/software/data-science-apis/.venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /Users/gwerbin/.local/share/proj
PROJ DATA (recommended version): 1.8
PROJ Database: 1.2
EPSG Database: v10.038 [2021-10-21]
ESRI Database: ArcMap 12.8 [2021-05-06]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.10.6 (main, Aug  3 2022, 03:22:45) [Clang 13.0.0 (clang-1300.0.29.30)]
executable: /Users/gwerbin/Projects/software/data-science-apis/.venv/bin/python
   machine: macOS-12.4-arm64-arm-64bit

Python deps:
/Users/gwerbin/Projects/software/data-science-apis/.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
   certifi: 2022.06.15
    Cython: None
setuptools: 65.3.0
       pip: 22.2.2
```

Output from `uname -a`:

```text
Darwin GWERBIN-MBP16.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

Output from the Mac utility `sw_vers`:

```text
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

#### Installation method

```sh
pyenv activate 3.10.6
python -m venv .venv
.venv/bin/pip install pyproj=3.3.1
```

**Comment by snowman2** [comment] 2022-08-26 15:51
@rouault, do you have any insight on this?

**Comment by rouault** [comment] 2022-08-26 23:22
@snowman2 what is the reference to identify there's a mismatch ? This comparison of SHA256 is done by pyproj itself right ?
no_kv_README.txt has been updated yesterday per https://github.com/OSGeo/PROJ-data/commit/b5cfc2aefeec49087855eefc88924fe23a92b080 and the CDN has been refreshed with it

**Comment by snowman2** [comment] 2022-08-27 00:37
@gwerbin, would you mind deleting the `/Users/gwerbin/.local/share/proj/files.geojson` file and trying again. I am wondering if your copy is out of date.

**Comment by snowman2** [comment] 2022-09-05 16:55
@gwerbin, thanks for the report. Haven't heard back from you, so going to assume that it is no longer an issue. If that is not the case, feel free to comment.

**Comment by gwerbin** [comment] 2022-09-05 17:31
Hi, no I simply got busy at work and forgot to try that. I will let you know what happens. However this error occurred on the very first time I ever tried to run this, so I would be surprised if I ended up with an out-of-date copy of anything.

**Comment by snowman2** [comment] 2022-09-06 01:51
I just tried it on a clean directory and the error is still there.

**Comment by snowman2** [comment] 2022-09-06 01:57
What is in `files.geojson`:
```
{'type': 'Feature', 'properties': {'url': 'https://cdn.proj.org/no_kv_README.txt', 'name': 'no_kv_README.txt', 'source': 'Kartverket (SK)', 'source_country': 'Norway', 'source_id': 'no_kv', 'source_url': 'https://www.kartverket.no/', 'file_size': 2787, 'sha256sum': 'da14b2599781950b1e203c70aeecb02dd98f19c1142587d2a760493c9026e660'}, 'geometry': None}
```
```
wget https://cdn.proj.org/no_kv_README.txt
...
$ openssl sha256 no_kv_README.txt 
SHA256(no_kv_README.txt)= 001f49df6ee612eb586a1877385222ed837054f046ac639eeace38daa29705ba
```
@rouault, there does appear to be a SHA256 mismatch. Is this something you can address?

**Comment by snowman2** [comment] 2022-09-06 02:01
For reference:
```python
from pyproj.sync import get_transform_grid_list
get_transform_grid_list(filename="no_kv_README.txt")
```

**Comment by rouault** [comment] 2022-09-06 07:34
> @rouault, there does appear to be a SHA256 mismatch. Is this something you can address?

should be fixed now after I've rerun the "sync_to_cdn.sh" script. I believe the previous attempt might have been prematurely interrupted

**Comment by rouault** [comment] 2022-09-06 07:34
to be clear files.geojson was out-of-date

**Comment by snowman2** [comment] 2022-09-06 15:02
Thanks @rouault - will test it out later.

**Comment by snowman2** [comment] 2022-09-07 01:43
The problem is resolved. Thanks @rouault :+1:

**Closed by snowman2** 2022-09-07 01:43 UTC
Labels: bug, proj
