### ISSUE TITLE
Error creating Transformer from CRS

### ISSUE THREAD

**Issue by ifarah** [pyproj4/pyproj#726] opened 2020-10-21 21:12 UTC
```python

import pyproj as proj
crs_wgs = proj.CRS('epsg:4326')
crs_nad = proj.CRS('epsg:4269')
x, y = proj.Transformer.from_crs(crs_wgs, crs_nad, always_xy=True).transform(23.731412, 37.992575)
print(x,y)

```
#### Problem description
![image](https://user-images.githubusercontent.com/22567155/96787723-dba68b80-13b7-11eb-87d9-9fe7d2dd5b38.png)
Transformer is not working
I tried using "+init=epsg:4269" and "+init=EPSG:4269" from reading previous issues, but these didn't work.
Not sure what's happening.

#### Expected Output
Change projections

#### Versions
Geopandas - '0.8.1'
proj - 2.6.1

$ conda list proj

![image (1)](https://user-images.githubusercontent.com/22567155/96787767-eeb95b80-13b7-11eb-9480-bb3ad607c254.png)

**Comment by snowman2** [comment] 2020-10-21 21:14
This guide should be helpful: https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select

**Comment by snowman2** [comment] 2020-10-21 21:16
Duplicate of #605

**Closed by snowman2** 2020-10-21 21:16 UTC
Labels: installation-issues

**Comment by ifarah** [comment] 2020-10-22 02:50
It seemed to be a problem with a specific version of pyproj.  It worked by installing a slightly earlier version:

pip install pyproj==2.6.0

**Comment by snowman2** [comment] 2020-10-22 13:05
> It seemed to be a problem with a specific version of pyproj. It worked by installing a slightly earlier version:

I notice that you are using conda. I would recommend installing pyproj using conda and not pip if you use conda.

```
conda create -n pyproj pyproj
conda activate pyproj
```

.condarc:
```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```
