### ISSUE TITLE
performance large number of transforms same datum

### ISSUE THREAD

**Issue by artttt** [pyproj4/pyproj#128] opened 2017-11-23 01:41 UTC
Ive noticed on my machine that  when running thousands of transforms if the 2 projections have the same datum then transform takes longer then doing calls on the proj instance/s.

If the check of having many points and datum match can done cheaply then there is a 10%+ (greater with more points it seems) speed up on the common case of not needing to change datum.

Im sure this is known and that is why calling a proj instance is in the api as is transform. However, Ive tended to use transform as a single call that can deal with moving between any 2 projections. I dont know how it works under the hood but maybe it can be adjusted to pick a faster route in these instances.

below is my timing testing
```
import pyproj
import numpy as np
import os, re

n = 100000

def datum_check():
    textfile = open(os.path.join(pyproj.pyproj_datadir,'epsg'), 'r')
    filetext = textfile.read()
    textfile.close()
    return re.findall(r"\n<(\d{4})>.*datum=WGS84", filetext)

epsg_with_wgs84_datum = datum_check()

for epsg in epsg_with_wgs84_datum:
    p1 = pyproj.Proj(init='epsg:3857')
    p2 = pyproj.Proj(init='EPSG:'+epsg)
    coords = (np.linspace(16000000, 17000000, num=n),np.linspace(-3000000, -4000000, num=n))
    same_projection = 'epsg:3857' in p2.srs
    epsg_srs = re.search(r'epsg:(\d{4})',p2.srs)
    same_datum = epsg_srs and epsg_srs.group(1) in epsg_with_wgs84_datum
    
    print epsg + ' transform time'
    %timeit f1 = pyproj.transform(p1, p2, *coords)
    f1 = pyproj.transform(p1, p2, *coords)
    if same_projection:
        print 'same projection'
        %timeit f2 = coords
        f2 = coords
    elif 'epsg:4326' in p2.srs:
        print 'same datum - geographic'
        #wgs84 plate carree projection ie geographic projection with same datum as epsg:3857
        %timeit f2 = p1(*coords,inverse=True)
        f2 = p1(*coords,inverse=True)
    elif same_datum:
        print 'same datum'
        %timeit f2 = p2(*p1(*coords,inverse=True))
        f2 = p2(*p1(*coords,inverse=True))
    else:
        print 'different datum full transform'
        %timeit f2 = pyproj.transform(p1, p2, *coords)
        f2 = pyproj.transform(p1, p2, *coords)
    print np.allclose(f1,f2)
```

**Comment by micahcochran** [comment] 2017-11-29 20:03
The question I have:  Should it be pyproj's responsibility or should this be the application's responsibility to detect if project A and B are the same?

How do you tell if two projections are the same?  To what level of certainty do you want that comparison to be?

`PROJ.4`'s 4.9.3 API currently doesn't have that functionality. http://proj4.org/development/api.html  There is talk about releasing a `PROJ.5` (5.0.0) and soon breaking the API, but I've not paid that much attention to the specifics.  A quick glance doesn't show a projection equality function.

I think you could definitely create code that would be able to do that.  It just is a matter of how much code is needed to do that. (I understand that it would be more pythonic.) 

The code in the repo would be easier to create this with `get_definition()`.

EPSG:3857 can be defined as 
`+init=epsg:3857`
OR
`+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs`

The algorithm will need to be able to parse PROJ.4 string and say if they are equal.  

If I remove `+no_def` and/or `+wktest` is it still EPSG:3857?

A couple years ago, I had a concern about lost precision when two projection are exactly the same.  So, I'm not against the idea.  It is just a problem that I have thought of and :man_shrugging: .

My answer is, it this is slightly more complicated than a quick fix.

**Comment by artttt** [comment] 2017-11-30 05:34
good question. As you say it is not a trivial task to detect if projection A = B then i think it makes sense for pyproj to do it right instead of the user working it out. It could be argued that its not pyprojs task to deal with coordinates in "numpy or regular python arrays, python lists/tuples or scalars" but that is handled to make life easier for the user. I dont think this is any different.

You are correct that a comprehensive check for all ways of defining the same projection becomes more complex. However it would be an easier starting point to check for simple common cases such as if both projections are defined with EPSG codes.
If the check isn't 100% definitive there is a fallback of just passing both projections to transform and letting it work it out.

An idea - Im not saying it is a good idea
It is possible to check if the projections are the same without parsing the proj.4 string by running transform for a sample of points and checking if the results are the "same" as the input. Obviously running checks like this are not worth while for converting a few points but it could be useful if projecting a lot of points. 
For fun i had a go at implementing this idea.

```
import copy
import pyproj
import numpy as np

def transform_picker(p1,p2):
    '''picks what should be the fastest pyproj projection method available for 2 projections
    
    returns a function that can be used to project coordinates.
    transformer = transform_picker(p1,p2)
    px,py = transformer(x,y)
    
    invalid coordinates in the output will be either infinity or 1e+30
    
    for small numbers of points in x,y this might not be the fastest
    for large numbers this usually saves about 10% but might save more in some cases.
    
    unfortunatly the picker can be slow to run so the savings of using the picker
    are probably not worth it unless transforming millions of points
    '''
    #for this demo ive ignored the z dimension
    #coordinates for the whole sphere every degree.
    #im assuming that all projections are valid over at least a few square degrees but i could be very wrong.
    coords = np.meshgrid(np.arange(-180,180),np.arange(-90,91))
    p_wgs = pyproj.Proj(init='epsg:4326')
    coordsBase = pyproj.transform(p_wgs, p1, *coords)
    f1 = pyproj.transform(p1, p2, *coordsBase)
    if np.allclose(f1,coordsBase):
        #no need to project
        return lambda x,y : copy.deepcopy((x,y))
    f2 = p1(*coordsBase,inverse=True)
    f2[0][f2[0]==1e+30] = np.inf
    f2[1][f2[1]==1e+30] = np.inf
    if np.allclose(f1,f2):
        #going to a geographic projection
        return lambda x,y : p1(x,y,inverse=True)
    
    f2 = p2(*coordsBase,inverse=False)
    f2[0][f2[0]==1e+30] = np.inf
    f2[1][f2[1]==1e+30] = np.inf
    if np.allclose(f1,f2):
        #coming from a geographic projection
        return lambda x,y : p2(x,y,inverse=False)
    
    f2 = p2(*p1(*coordsBase,inverse=True))
    f2[0][f2[0]==1e+30] = np.inf
    f2[1][f2[1]==1e+30] = np.inf
    if np.allclose(f1,f2):
        #between to projections same datum
        return lambda x,y : p2(*p1(x,y,inverse=True))
    #last option is it needs a datum transform or some other issue fall back to a transform
    return lambda x,y : pyproj.transform(p1, p2, x,y)


p1 = pyproj.Proj('+init=epsg:3857')
p2 = pyproj.Proj(
    '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs')
transformer = transform_picker(p1,p2)
print transformer(1,1)
#compare timing to show that the picker picked a fast option
n= 100000
coords = (np.linspace(16000000, 17000000, num=n),np.linspace(-3000000, -4000000, num=n))
%timeit pyproj.transform(p1, p2, *coords)
%timeit transformer(*coords)
```

**Comment by micahcochran** [comment] 2017-11-30 14:47
At the top of the `transform` function a simple equality between two projections for using either `srs` string or the `definition_string()` would detect the most obvious cases.

You could submit a pull request for this.

**Comment by snowman2** [comment] 2019-03-16 14:48
Great ideas here. The new CRS class has the ability to compare projections [here](https://github.com/pyproj4/pyproj/blob/b6b73504a10087dbb928a3733c7280bae98f8376/pyproj/_crs.pyx#L587), so this could be used. I agree with @micahcochran that this is something to be careful about. In this vein, I propose having a flag in the transform function to skip reprojection if they are the same that defaults to false.

**Comment by snowman2** [comment] 2019-03-16 14:50
@kbevers @rouault, how is this handled currently in PROJ?

**Comment by kbevers** [comment] 2019-03-16 15:08
You can use `proj_is_equivalent_to` to check if two CRS's are likely to be the same. If they are, a "no-op" operation can be instantiated using a parameter-less affine transformation (`+proj=affine` without any parameters constitutes a no-op).

**Comment by snowman2** [comment] 2019-03-16 18:59
Thanks @kbevers!

**Comment by snowman2** [comment] 2019-03-19 03:37
Solution merged into master. Thanks for sharing this use case/idea!

**Comment by artttt** [comment] 2019-03-19 05:53
Wow lots of work on this package lately. great stuff. Thanks for picking up my idea and implementing it.

I will preface this by saying maybe this is redundant now as i haven't tried pyproj 2+ yet?

The other optimisation explored in the opening post that i dont think has been done here is that transform is slower when a datum transform is not needed.

so....
if going to or from geographic coordinates with the same datum
eg this is faster
`p1(*coords,inverse=True)`
than transform
`pyproj.transform(p1, p2, *coords)`

There is also an alternative for going between 2 projected coordinate systems with the same datum
`p2(*p1(*coords,inverse=True))`
but the speedup isnt as large and is slower for a small number of coord pairs.

So while the option to use these faster routes exist as shown above many users just go straight for 'transform' and users of packages like geopandas have transform hard coded in.
(https://github.com/geopandas/geopandas/blob/b01e62adc0861fdb18f7e302d5ff7f57cf3f94e8/geopandas/geoseries.py#L302)

**Comment by snowman2** [comment] 2019-03-19 12:11
I think this might help: https://github.com/pyproj4/pyproj/blob/master/sphinx/optimize_transformations.rst

**Comment by snowman2** [comment] 2019-03-19 12:13
Maybe adding notes there with specific examples could be useful for other users.

**Comment by snowman2** [comment] 2019-03-19 12:26
Mind sharing specific examples here or adding them in a PR to the docs link?

**Comment by artttt** [comment] 2019-03-19 23:43
With a view to providing an example i installed  2.1.1
To try out
https://github.com/pyproj4/pyproj/blob/master/sphinx/optimize_transformations.rst

I noted 2 things:
1) the optimisations i discussed above do not have a clear advantage over using a transformer (as long as you ignore the time to create the transformer)
2) on my machine 2.1.1 is slow compared to 1.9.6

So  in light of point 1 i dont think there is value in an example and point 2 probably best covered in a different issue.

Below is how i tested and results for each version (in a jupyter notebook for the timeit magic)
```
import pyproj
import numpy as np

print (f"pyproj version number is : {pyproj.__version__}")

if pyproj.__version__[0] == '2':
    %time transformer = pyproj.Transformer.from_proj(3857, 4326)

p1 = pyproj.Proj(init='epsg:3857') #Web Mercator
p2 = pyproj.Proj(init='epsg:4326') #WGS 84 long lats

for exponent in range(0, 7):
    n = 10 ** exponent
    print (f"{n} coordinate pairs")
    coords = (np.linspace(16000000, 17000000, num=n),np.linspace(-3000000, -4000000, num=n))
    print ("transform   ", end=" ")
    %timeit -r1 f1 = pyproj.transform(p1, p2, *coords)
    if pyproj.__version__[0] == '2':
        print ("transformer ", end=" ")
        %timeit -r1 f2 = transformer.transform(*coords)
    print ("proj        ", end=" ")
    %timeit -r1 f3 = p1(*coords,inverse=True)
    print ("")

pyproj version number is : 1.9.6
1 coordinate pairs
transform    9.85 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)
proj         8.22 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

10 coordinate pairs
transform    10.4 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)
proj         8.75 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

100 coordinate pairs
transform    19 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)
proj         15.1 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

1000 coordinate pairs
transform    107 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)
proj         68.9 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)

10000 coordinate pairs
transform    960 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         583 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

100000 coordinate pairs
transform    9.81 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
proj         7.72 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

1000000 coordinate pairs
transform    100 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
proj         61.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)

pyproj version number is : 2.1.1
CPU times: user 30 ms, sys: 10 ms, total: 40 ms
Wall time: 45 ms
1 coordinate pairs
transform    26.5 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  8.25 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)
proj         9.45 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

10 coordinate pairs
transform    25.5 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  12.6 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)
proj         13.3 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

100 coordinate pairs
transform    25.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  51.8 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)
proj         58.4 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)

1000 coordinate pairs
transform    25.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  453 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         496 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

10000 coordinate pairs
transform    29.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  4.65 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
proj         5.86 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

100000 coordinate pairs
transform    69.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
transformer  45.2 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
proj         51.5 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)

1000000 coordinate pairs
transform    452 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
transformer  469 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
proj         467 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

**Comment by snowman2** [comment] 2019-03-20 01:05
Interesting 🤔

**Comment by artttt** [comment] 2019-03-20 05:51
further to my last post v2.0.0 seems to run as a speed about half way between 1.9.6 and 2.1.1

```
pyproj version number is : 2.0.0
1 coordinate pairs
transform    1.07 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         9.09 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

10 coordinate pairs
transform    965 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         11.8 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 100000 loops each)

100 coordinate pairs
transform    980 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         45.6 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10000 loops each)

1000 coordinate pairs
transform    1.26 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
proj         341 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

10000 coordinate pairs
transform    3.46 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
proj         3.18 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

100000 coordinate pairs
transform    26.2 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)
proj         37.5 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)

1000000 coordinate pairs
transform    292 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
proj         288 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

**Comment by artttt** [comment] 2019-03-21 00:14
Since this issue is closed should we reopen or make a new issue for the performance slowdown noticed?

Ive tried digging into the changes that might have led to the slowdown between 1.9.6 and 2.0.0 thinking i would be able to identify what changed. However the huge amount of change in commit 38dfd7bb32bbfd5e2c31e97ecaf1024334eea632 is too much for me to get my head around so im hoping those with more pyproj experience will get to the bottom of it.

**Comment by jswhit** [comment] 2019-03-21 01:27
Seems likely to me that it is due to changes in the C library and/or extra overhead in the C API.  I see no reason why pyproj itself would be slower (if you neglect the overhead of creating the Transformer object).

**Comment by jswhit** [comment] 2019-03-21 01:28
Still, I think it is worth keeping this open so we can collect more detailed profiling information and try to narrow down the cause.

**Comment by artttt** [comment] 2019-03-21 05:20
more info
if i do the following then 2.1.1 performs like 2.0.0 (ie faster but not as fast as 1.9.6)
```
conda install -y -c conda-forge proj4
pip install git+https://github.com/pyproj4/pyproj.git@v2.1.1rel  --force-reinstall
```
however, this is slower

`pip install pyproj==2.1.1 --force-reinstall`

2.0.0 performs the same with either install method
2.0.1 and onwards have this issue

so a difference between building from source v installing from a wheel that didn't affect the 2.0.0 wheel.

I think that narrows it down to the change in the wheel building tooling probably not a change in the C library.
feac3b6351de2f8127640c5f43ffd0a51510f756
2254266ab167128f99d1d4542f9d45ddfa10b700


The 1.96 - 2.0.0 difference might be in the c library though.

**Comment by snowman2** [comment] 2019-06-09 00:59
@artttt, thanks for investigating this further. Maybe upgrading to the [manylinux2010](https://www.python.org/dev/peps/pep-0571/) instead if [manylinux1](https://www.python.org/dev/peps/pep-0513/) will provide speedups with newer compilers.

Tracking issue for manylinux2010 is [here](https://github.com/pypa/manylinux/issues/179).

**Comment by snowman2** [comment] 2019-10-30 22:25
Closing for preference for

**Closed by snowman2** 2019-10-30 22:25 UTC
Labels: enhancement, proposal
