### ISSUE TITLE
Incorrect transformation results when using EPSG 2263 (NY State Plane, feet US)

### ISSUE THREAD

**Issue by ddohler** [pyproj4/pyproj#67] opened 2016-04-05 21:18 UTC
With PyProj:

``` python
import pyproj
wgs84 = pyproj.Proj("+init=EPSG:4326")
ny_state = pyproj.Proj("+init=EPSG:2263")
pyproj.transform(wgs84, ny_state, -74.01720548026697, 40.641305906460005)
```

Result: `(298544.59235271334, 52706.69470216743)`

Compare to `gdaltransform`:

```
$ gdaltransform -s_srs EPSG:4326 -t_srs EPSG:2263
-74.01720548026697, 40.641305906460005
979475.050077194 172921.880868694 0
```

By contrast, PyProj and GDAL agree when transforming to WebMercator:

```
webmerc = pyproj.Proj("+init=EPSG:3857")
pyproj.transform(wgs84, webmerc, -74.01720548026697, 40.641305906460005)
```

Result: `(-8239557.624004417, 4959577.466271832)`

```
gdaltransform -s_srs EPSG:4326 -t_srs EPSG:3857
-74.01720548026697, 40.641305906460005
-8239557.62400442 4959577.46627184 0
```

**Comment by micahcochran** [comment] 2016-04-06 01:22
EPSG:2263 is a state plane coordinate system "NAD83 / New York Long Island (ftUS)".  I assume it is US Survey Feet.

You need to set the preserve_units flag to True.  Otherwise, pyproj will set your coordinate units to meters.

IPython console to show my work.  
```
In [1]: import pyproj

In [2]: ny_state = pyproj.Proj(init="EPSG:2263", preserve_units=True)

In [3]: ny_state(-74.01720548026697, 40.641305906460005)
Out[3]: (979475.050077198, 172921.88086868977)
```

Calling ny_state() as a function does a transform to epsg:4326, as a shortcut.  Your above code should also work when you add the preserve_units=True flag.

This is not an isolated incident, other get tripped up by this too.  (Duplicate of #58 , #40)

**Comment by JamesFysh** [comment] 2017-05-03 10:41
> This is not an isolated incident, other get tripped up by this too.

I just came here to raise an issue also (transforming from epsg:4326 -> epsg:102697 AKA NAD_1983_StatePlane_Missouri_Central_FIPS_2402_Feet) where I was finding that the resulting coordinates were given in meters, not us-ft as expected.

It all makes more sense now, although I wonder: What is the purpose of the preserve_units parameter?  It seems like it should at least be set to True by default, as the current behavior is clearly unexpected.

**Comment by kevhill** [comment] 2018-08-28 02:02
what's the rationale behind defaulting to `preserve_units=False`? This cost me probably 4 hours of time, and obviously, this is affecting multiple people. I can't see any reason why you would ever have a default that ignored specific information entered in elsewhere.

**Comment by snowman2** [comment] 2019-03-23 03:29
Closing as `preserve_units=True` is now the default in pyproj>=2.0.0

**Closed by snowman2** 2019-03-23 03:29 UTC
